module.exports = {
    head1:{
        color:'black',
        fontSize:30,
        textAlign:'center'
    },
    head2:{
        color:'black',
        fontSize:20,
        textAlign:'center'
    },
    formgroup:{
        display:'flex'
      },
      label:{
        fontSize:17,
        color:'black',
        marginBottom:3
      },
      input:{
        backgroundColor:'#c6cf67',
        borderRadius:20,
        paddingHorizontal:10,
        paddingVertical:8,
      },
      link:{
        fontSize:17,
      },
      button1:{
        backgroundColor:'#B5C135',
        color:'black',
        padding:10,
        borderRadius:20,
        height:50,
        fontSize:20,
        width:300,
        textAlig:'center',
        margin:10,
        textAlign:'center'
      }
}